import { STATIC_ROUNDS_URL } from '../constants'

const requests = new Map()

// Rounds are static files served by the CDN (generated by scripts/export-static-rounds.mjs),
// so dealing cards costs no Firestore reads. Ranked answers are not in these files.
function loadRound(roundId) {
  if (!requests.has(roundId)) {
    const request = fetch(`${STATIC_ROUNDS_URL}/${roundId}.json`)
      .then((response) => {
        if (!response.ok) throw new Error('round-not-found')
        return response.json()
      })
      .catch((error) => {
        requests.delete(roundId)
        throw error
      })
    requests.set(roundId, request)
  }
  return requests.get(roundId)
}

export async function getRound(roundId) {
  const { cards } = await loadRound(roundId)
  return { id: roundId, cards }
}

export async function getGuestAnswer(roundId) {
  const { answer } = await loadRound(roundId)
  if (!answer) throw new Error('answer-not-found')
  return answer
}
