import React from 'react'

const content = {
  privacy: {
    'pt-BR': ['Política de Privacidade','O When? usa autenticação do Google apenas para identificar sua conta. O jogo não exibe sua foto nem seu nome do Google no ranking. O único nome público é o nickname escolhido por você.','No modo visitante, não criamos registros de tentativas, partidas, pontuações, Analytics ou dados pessoais. Depois do login, armazenamos no Firebase o identificador da conta, nickname, país inferido pelo idioma/região do navegador, tentativas diárias, partidas, pontuações e dados necessários para o ranking. Não vendemos dados pessoais.','Para jogadores autenticados, usamos Google Analytics para entender o uso agregado, como páginas acessadas e eventos de gameplay. Imagens das cartas podem ser carregadas do Wikimedia Commons.','Você pode deixar de usar o serviço a qualquer momento. Para solicitar remoção dos dados vinculados à conta, utilize o canal de contato publicado no repositório oficial do projeto.'],
    en: ['Privacy Policy','When? uses Google authentication only to identify your account. Your Google photo and Google display name are not shown on the leaderboard. The only public name is the nickname you choose.','Guest mode creates no attempt, game, score, Analytics, or personal-data records. After sign-in, Firebase stores your account identifier, nickname, browser-inferred country, daily attempts, games, scores, and leaderboard data. We do not sell personal data.','For authenticated players, Google Analytics is used to understand aggregate usage such as page views and gameplay events. Card images may be loaded from Wikimedia Commons.','You can stop using the service at any time. To request deletion of account-linked data, use the contact channel published in the official project repository.'],
  },
  terms: {
    'pt-BR': ['Termos de Uso','When? é um jogo de conhecimento e entretenimento. As datas são apresentadas no nível de precisão indicado no banco do jogo e alguns eventos históricos podem utilizar datas tradicionais ou aproximadas.','Cada conta pode iniciar até três partidas por dia. Tentativas, pontuações e ranking são controlados no Firebase. Qualquer tentativa de manipular o cliente, contornar limites ou adulterar pontuações pode resultar na exclusão desses registros.','O conteúdo visual de terceiros, quando utilizado, mantém sua atribuição e licença indicadas pela fonte. O jogo pode ser alterado, suspenso ou atualizado sem aviso prévio.'],
    en: ['Terms of Use','When? is a knowledge and entertainment game. Dates use the precision recorded in the game database, and some historical events may rely on traditional or approximate dating.','Each account may start up to three games per day. Attempts, scores, and leaderboard data are controlled through Firebase. Attempts to tamper with the client, bypass limits, or manipulate scores may result in those records being removed.','Third-party visual content keeps the attribution and license indicated by its source. The game may be changed, suspended, or updated without prior notice.'],
  },
}

export default function LegalPage({ type, language }) {
  const [title,...paragraphs]=content[type][language]||content[type]['pt-BR']
  return <article className="page-card legal-page"><h1>{title}</h1>{paragraphs.map((p,i)=><p key={i}>{p}</p>)}<small>Última atualização / Last updated: 21/09/2026.</small></article>
}
