// Writes static HTML for every public page, plus sitemap.xml, robots.txt, llms.txt and
// Netlify's _redirects, from the Node build of the app (dist-ssr/). Runs as the last step
// of `npm run build`:
//
//   vite build                                     -> dist/ (browser app, index.html template)
//   vite build --ssr src/entry-server.jsx ...      -> dist-ssr/ (same app, for Node)
//   node scripts/prerender.mjs                     -> dist/*.html, sitemap, robots, ...
//
// Each page is a real HTML document with its content, title, description, canonical,
// hreflang, social tags and JSON-LD. The browser then hydrates it into the live app, so
// crawlers read the content without running JavaScript and players get the same SPA.
import fs from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const dist = path.join(root, 'dist')
const ssrDir = path.join(root, 'dist-ssr')

const server = await import(pathToFileURL(path.join(ssrDir, 'entry-server.js')).href)
const { render, listPages, SITE_URL, absoluteUrl } = server
const template = await fs.readFile(path.join(dist, 'index.html'), 'utf8')

// Search Console's HTML-tag verification (needed on a *.netlify.app address, where a DNS
// record cannot be added). Set GOOGLE_SITE_VERIFICATION to the token Google shows.
const verification = process.env.GOOGLE_SITE_VERIFICATION?.trim()
const verificationTag = verification
  ? `<meta name="google-site-verification" content="${verification.replace(/"/g, '')}" />`
  : ''

const fileFor = (pagePath) => (pagePath === '/' ? 'index.html' : `${pagePath.slice(1)}.html`)

function fill(page) {
  const replacements = [
    ['<html lang="pt-BR">', `<html lang="${page.language}">`],
    [/<!--app-head-->[\s\S]*?<!--\/app-head-->/, page.head],
    ['<!--search-console-->', verificationTag],
    [
      '<div id="root"><!--app-html--></div>',
      `<div id="root" data-route="${page.routeKey}">${page.html}</div>`,
    ],
  ]
  return replacements.reduce((html, [from, to]) => {
    if (typeof from === 'string' ? !html.includes(from) : !from.test(html)) {
      throw new Error(`index.html is missing the placeholder ${from}`)
    }
    return html.replace(from, () => to)
  }, template)
}

async function writePage(file, html) {
  const target = path.join(dist, file)
  await fs.mkdir(path.dirname(target), { recursive: true })
  await fs.writeFile(target, html)
}

// --- Pages ------------------------------------------------------------------------------

const pages = await listPages()
const rendered = new Map()
for (const pagePath of pages) {
  const page = await render(pagePath)
  rendered.set(pagePath, page)
  await writePage(fileFor(pagePath), fill(page))
}

// Shared pages: every challenge link is served the challenge page of its language, and
// every unknown address the 404 page (Netlify sends 404.html with a 404 status).
const shells = {
  'desafio.html': '/desafio/codigo',
  'challenge.html': '/challenge/code',
  '404.html': '/404',
}
for (const [file, pagePath] of Object.entries(shells)) {
  await writePage(file, fill(await render(pagePath)))
}

// --- Netlify rewrites -----------------------------------------------------------------------

// Each page is served at its clean address (/sobre, not /sobre.html). Listing them keeps
// that independent of Netlify's "pretty URLs" setting; anything not listed gets 404.html.
const redirects = [
  '# Generated by scripts/prerender.mjs. Do not edit.',
  ...pages.filter((p) => p !== '/').map((p) => `${p}  ${p}.html  200`),
  '/desafio/*  /desafio.html  200',
  '/challenge/*  /challenge.html  200',
]
await fs.writeFile(path.join(dist, '_redirects'), `${redirects.join('\n')}\n`)

// --- sitemap.xml ----------------------------------------------------------------------------

const xml = (value) => value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
const indexable = [...rendered.entries()].filter(([, page]) => page.indexable)
const sitemap = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">',
  ...indexable.map(([pagePath, page]) =>
    [
      '  <url>',
      `    <loc>${xml(absoluteUrl(pagePath))}</loc>`,
      ...page.alternates.map(
        (link) =>
          `    <xhtml:link rel="alternate" hreflang="${link.hreflang}" href="${xml(link.href)}" />`,
      ),
      '  </url>',
    ].join('\n'),
  ),
  '</urlset>',
].join('\n')
await fs.writeFile(path.join(dist, 'sitemap.xml'), `${sitemap}\n`)

// --- robots.txt and llms.txt ----------------------------------------------------------------

const robots = [
  'User-agent: *',
  'Allow: /',
  // Game data files and challenge links are not pages worth indexing.
  'Disallow: /rounds/',
  'Disallow: /desafio/',
  'Disallow: /challenge/',
  '',
  `Sitemap: ${SITE_URL}/sitemap.xml`,
].join('\n')
await fs.writeFile(path.join(dist, 'robots.txt'), `${robots}\n`)

const llms = [
  '# When?',
  '',
  'When? is a free, bilingual (PT-BR / English) browser chronology game: players put historical events in order, from oldest to newest, over six rounds of four cards. The name is never translated.',
  '',
  '- Normal mode: no clock, playable signed in or not, never affects the leaderboard.',
  '- Ranked mode: Google sign-in, 40 seconds per round, up to three games a day; only ranked games score on the leaderboard, and scores are checked by Cloud Firestore security rules.',
  '',
  `Home (Português): ${absoluteUrl('/')}`,
  `Home (English): ${absoluteUrl('/en')}`,
  `How to play: ${absoluteUrl('/how-to-play')}`,
  `Historical facts: ${absoluteUrl('/history')}`,
  `Leaderboard: ${absoluteUrl('/leaderboard')}`,
  `Sitemap: ${SITE_URL}/sitemap.xml`,
].join('\n')
await fs.writeFile(path.join(dist, 'llms.txt'), `${llms}\n`)

// --- Checks ---------------------------------------------------------------------------------

// Fail the build rather than publish a page with broken SEO or a dead internal link.
const problems = []
const known = new Set([...pages])
for (const [pagePath, page] of rendered) {
  const html = fill(page)
  const where = `${pagePath}:`
  if (!/<title>[^<]{10,}<\/title>/.test(html)) problems.push(`${where} missing title`)
  if (!html.includes('name="description"')) problems.push(`${where} missing description`)
  if (page.indexable && !html.includes('rel="canonical"'))
    problems.push(`${where} missing canonical`)
  if ((html.match(/<h1[\s>]/g) || []).length !== 1)
    problems.push(`${where} must have exactly one <h1>`)
  for (const [, json] of html.matchAll(
    /<script type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/g,
  )) {
    try {
      JSON.parse(json)
    } catch {
      problems.push(`${where} invalid JSON-LD`)
    }
  }
  for (const [, href] of html.matchAll(/<a [^>]*href="(\/[^"#?]*)/g)) {
    if (!known.has(href)) problems.push(`${where} links to ${href}, which is not a generated page`)
  }
}
await fs.rm(ssrDir, { recursive: true, force: true })

if (problems.length) {
  console.error(`Prerender found ${problems.length} problem(s):\n${problems.join('\n')}`)
  process.exit(1)
}
console.log(
  `Prerendered ${rendered.size} pages (+${Object.keys(shells).length} shared) for ${SITE_URL}`,
)
console.log(`sitemap.xml: ${indexable.length} URLs · robots.txt · llms.txt · _redirects`)
